In [1]:
# pull in dependencies
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress
import numpy as np
from sklearn import datasets

import seaborn as sns

In [2]:
y_2015 = pd.read_csv('2015.csv')
y_2016 = pd.read_csv('2016.csv')
y_2017 = pd.read_csv('2017.csv')
y_2018 = pd.read_csv('2018.csv')
y_2019 = pd.read_csv('2019.csv')
y_2020 = pd.read_csv('2020.csv')
y_2021 = pd.read_csv('2021.csv')
y_2020

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Myanmar,Southeast Asia,4.3080,0.042949,4.392180,4.223820,8.680482,0.784407,58.961712,0.895075,0.560664,0.645124,1.972317,0.678091,1.098178,0.495443,0.597479,0.569814,0.187530,0.681463
1,Indonesia,Southeast Asia,5.2856,0.047692,5.379077,5.192123,9.369752,0.808380,62.155849,0.870614,0.519587,0.876296,1.972317,0.891721,1.154801,0.610437,0.568161,0.542647,0.038279,1.479573
2,Haiti,Latin America and Caribbean,3.7208,0.101463,3.919667,3.521932,7.411329,0.593248,55.598625,0.537825,0.400535,0.684767,1.972317,0.284734,0.646671,0.374367,0.169298,0.463910,0.161936,1.619917
3,Gambia,Sub-Saharan Africa,4.7506,0.067164,4.882241,4.618959,7.321815,0.693169,55.012016,0.733163,0.343199,0.690718,1.972317,0.256991,0.882679,0.353248,0.403420,0.425990,0.158094,2.270216
4,Kenya,Sub-Saharan Africa,4.5830,0.067805,4.715898,4.450102,8.029776,0.702652,60.096931,0.829748,0.294682,0.831499,1.972317,0.476413,0.905078,0.536313,0.519181,0.393902,0.067201,1.684905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Azerbaijan,Commonwealth of Independent States,5.1648,0.034197,5.231827,5.097774,9.687727,0.819308,65.508400,0.786824,-0.240255,0.552538,1.972317,0.990273,1.180613,0.731134,0.467735,0.040113,0.247307,1.507633
149,Morocco,Middle East and North Africa,5.0948,0.055650,5.203875,4.985725,8.940313,0.592628,65.896240,0.772072,-0.240377,0.815725,1.972317,0.758622,0.645208,0.745097,0.450054,0.040033,0.077386,2.378402
150,Japan,East Asia,5.8708,0.041392,5.951928,5.789672,10.579689,0.883546,75.000969,0.809961,-0.246910,0.654558,1.972317,1.266724,1.332339,1.072881,0.495466,0.035712,0.181440,1.486200
151,Botswana,Sub-Saharan Africa,3.4789,0.060543,3.597564,3.360236,9.711204,0.779122,58.924454,0.821328,-0.250394,0.777931,1.972317,0.997549,1.085695,0.494102,0.509089,0.033407,0.101786,0.257241
152,Greece,Western Europe,5.5150,0.046932,5.606986,5.423014,10.132326,0.814380,72.405258,0.541345,-0.300907,0.859931,1.972317,1.128070,1.168974,0.979432,0.173516,0.000000,0.048844,2.016179

In [3]:
#add year column with corresponding year of file
y_2015['Year']="2015"
y_2016['Year']="2016"
y_2017['Year']="2017"
y_2018['Year']="2018"
y_2019['Year']="2019"
y_2020['Year']="2020"
y_2021['Year']="2021"

#Cleanup column names to be uniform and the same across all DF before merging
y_2015 = y_2015.rename(columns={'Economy (GDP per Capita)':'GDP'})
y_2016 = y_2016.rename(columns={'Economy (GDP per Capita)':'GDP'})
y_2017 = y_2017.rename(columns={'Economy..GDP.per.Capita.':'GDP', 'Happiness.Score':'Happiness Score'})
y_2018 = y_2018.rename(columns={'Country or region':'Country','GDP per capita':'GDP', 'Score': 'Happiness Score'})
y_2019 = y_2019.rename(columns={'Country or region':'Country','GDP per capita': 'GDP',
                               'Score': 'Happiness Score'})
y_2020 = y_2020.rename(columns={'Country name':'Country', 'Explained by: Log GDP per capita': 'GDP',
                                'Generosity':'ng','Explained by: Generosity': 'Generosity','Ladder score': 'Happiness Score'})
y_2021 = y_2021.rename(columns={'Country name':'Country','Explained by: Log GDP per capita': 'GDP', 
                                'Generosity':'ng','Explained by: Generosity': 'Generosity','Ladder score': 'Happiness Score'})


df2015 = y_2015[['Country','Happiness Score','GDP','Freedom','Generosity','Year','Trust (Government Corruption)']]
df2016 = y_2016[['Country','Happiness Score','GDP','Freedom','Generosity','Year','Trust (Government Corruption)']]
df2017 = y_2017[['Country','Happiness Score','GDP','Freedom','Generosity','Year','Trust..Government.Corruption.']]
df2018 = y_2018[['Country','Happiness Score','GDP','Freedom to make life choices','Generosity','Year','Perceptions of corruption']]
df2019 = y_2019[['Country','Happiness Score','GDP','Freedom to make life choices','Generosity','Year','Perceptions of corruption']]
df2020 = y_2020[['Country','Happiness Score','GDP','Freedom to make life choices','Generosity','Year','Perceptions of corruption']]
df2021 = y_2021[['Country','Happiness Score','GDP','Freedom to make life choices','Generosity','Year','Perceptions of corruption']]

In [ ]:
#y_2021.sort_values('Happiness Score', ascending=False)

In [18]:
df2015.columns=[]

ValueError: Length mismatch: Expected axis has 7 elements, new values have 2 elements

In [5]:
combined_years = pd.merge(df2015, df2016, how='outer', on='Country')
combined_years.head()

,Country,Happiness Score_x,GDP_x,Freedom_x,Generosity_x,Year_x,Trust (Government Corruption)_x,Happiness Score_y,GDP_y,Freedom_y,Generosity_y,Year_y,Trust (Government Corruption)_y
0,Switzerland,7.587,1.39651,0.66557,0.29678,2015,0.41978,7.509,1.52733,0.58557,0.28083,2016,0.41203
1,Iceland,7.561,1.30232,0.62877,0.43630,2015,0.14145,7.501,1.42666,0.56624,0.47678,2016,0.14975
2,Denmark,7.527,1.32548,0.64938,0.34139,2015,0.48357,7.526,1.44178,0.57941,0.36171,2016,0.44453
3,Norway,7.522,1.45900,0.66973,0.34699,2015,0.36503,7.498,1.57744,0.59609,0.37895,2016,0.35776
4,Canada,7.427,1.32629,0.63297,0.45811,2015,0.32957,7.404,1.44015,0.57370,0.44834,2016,0.31329

In [6]:
combined_years = pd.merge(combined_years, df2017, how='outer', on='Country')
combined_years.head()

,Country,Happiness Score_x,GDP_x,Freedom_x,Generosity_x,Year_x,Trust (Government Corruption)_x,Happiness Score_y,GDP_y,Freedom_y,Generosity_y,Year_y,Trust (Government Corruption)_y,Happiness Score,GDP,Freedom,Generosity,Year,Trust..Government.Corruption.
0,Switzerland,7.587,1.39651,0.66557,0.29678,2015,0.41978,7.509,1.52733,0.58557,0.28083,2016,0.41203,7.494,1.564980,0.620071,0.290549,2017,0.367007
1,Iceland,7.561,1.30232,0.62877,0.43630,2015,0.14145,7.501,1.42666,0.56624,0.47678,2016,0.14975,7.504,1.480633,0.627163,0.475540,2017,0.153527
2,Denmark,7.527,1.32548,0.64938,0.34139,2015,0.48357,7.526,1.44178,0.57941,0.36171,2016,0.44453,7.522,1.482383,0.626007,0.355280,2017,0.400770
3,Norway,7.522,1.45900,0.66973,0.34699,2015,0.36503,7.498,1.57744,0.59609,0.37895,2016,0.35776,7.537,1.616463,0.635423,0.362012,2017,0.315964
4,Canada,7.427,1.32629,0.63297,0.45811,2015,0.32957,7.404,1.44015,0.57370,0.44834,2016,0.31329,7.316,1.479204,0.611101,0.435540,2017,0.287372

In [7]:
combined_years = pd.merge(combined_years, df2018, how='outer', on='Country')
combined_years.head()

,Country,Happiness Score_x,GDP_x,Freedom_x,Generosity_x,Year_x,Trust (Government Corruption)_x,Happiness Score_y,GDP_y,Freedom_y,...,Freedom,Generosity_x,Year_x,Trust..Government.Corruption.,Happiness Score_y,GDP_y,Freedom to make life choices,Generosity_y,Year_y,Perceptions of corruption
0,Switzerland,7.587,1.39651,0.66557,0.29678,2015,0.41978,7.509,1.52733,0.58557,...,0.620071,0.290549,2017,0.367007,7.487,1.420,0.660,0.256,2018,0.357
1,Iceland,7.561,1.30232,0.62877,0.43630,2015,0.14145,7.501,1.42666,0.56624,...,0.627163,0.475540,2017,0.153527,7.495,1.343,0.677,0.353,2018,0.138
2,Denmark,7.527,1.32548,0.64938,0.34139,2015,0.48357,7.526,1.44178,0.57941,...,0.626007,0.355280,2017,0.400770,7.555,1.351,0.683,0.284,2018,0.408
3,Norway,7.522,1.45900,0.66973,0.34699,2015,0.36503,7.498,1.57744,0.59609,...,0.635423,0.362012,2017,0.315964,7.594,1.456,0.686,0.286,2018,0.340
4,Canada,7.427,1.32629,0.63297,0.45811,2015,0.32957,7.404,1.44015,0.57370,...,0.611101,0.435540,2017,0.287372,7.328,1.330,0.653,0.321,2018,0.291

In [8]:
combined_years = pd.merge(combined_years, df2019, how='outer', on='Country')
combined_years.head()

,Country,Happiness Score_x,GDP_x,Freedom_x,Generosity_x,Year_x,Trust (Government Corruption)_x,Happiness Score_y,GDP_y,Freedom_y,...,Freedom to make life choices_x,Generosity_y,Year_y,Perceptions of corruption_x,Happiness Score,GDP,Freedom to make life choices_y,Generosity,Year,Perceptions of corruption_y
0,Switzerland,7.587,1.39651,0.66557,0.29678,2015,0.41978,7.509,1.52733,0.58557,...,0.660,0.256,2018,0.357,7.480,1.452,0.572,0.263,2019,0.343
1,Iceland,7.561,1.30232,0.62877,0.43630,2015,0.14145,7.501,1.42666,0.56624,...,0.677,0.353,2018,0.138,7.494,1.380,0.591,0.354,2019,0.118
2,Denmark,7.527,1.32548,0.64938,0.34139,2015,0.48357,7.526,1.44178,0.57941,...,0.683,0.284,2018,0.408,7.600,1.383,0.592,0.252,2019,0.410
3,Norway,7.522,1.45900,0.66973,0.34699,2015,0.36503,7.498,1.57744,0.59609,...,0.686,0.286,2018,0.340,7.554,1.488,0.603,0.271,2019,0.341
4,Canada,7.427,1.32629,0.63297,0.45811,2015,0.32957,7.404,1.44015,0.57370,...,0.653,0.321,2018,0.291,7.278,1.365,0.584,0.285,2019,0.308

In [9]:
combined_years = pd.merge(combined_years, df2020, how='outer', on='Country')
combined_years.head()

,Country,Happiness Score_x,GDP_x,Freedom_x,Generosity_x,Year_x,Trust (Government Corruption)_x,Happiness Score_y,GDP_y,Freedom_y,...,Freedom to make life choices_y,Generosity_x,Year_x,Perceptions of corruption_y,Happiness Score_y,GDP_y,Freedom to make life choices,Generosity_y,Year_y,Perceptions of corruption
0,Switzerland,7.587,1.39651,0.66557,0.29678,2015,0.41978,7.509,1.52733,0.58557,...,0.572,0.263,2019,0.343,7.5599,1.390774,0.921337,0.269056,2020,0.303728
1,Iceland,7.561,1.30232,0.62877,0.43630,2015,0.14145,7.501,1.42666,0.56624,...,0.591,0.354,2019,0.118,7.5045,1.326502,0.948892,0.362330,2020,0.711710
2,Denmark,7.527,1.32548,0.64938,0.34139,2015,0.48357,7.526,1.44178,0.57941,...,0.592,0.252,2019,0.410,7.6456,1.326949,0.951444,0.242793,2020,0.168489
3,Norway,7.522,1.45900,0.66973,0.34699,2015,0.36503,7.498,1.57744,0.59609,...,0.603,0.271,2019,0.341,7.4880,1.424207,0.955750,0.287985,2020,0.263218
4,Canada,7.427,1.32629,0.63297,0.45811,2015,0.32957,7.404,1.44015,0.57370,...,0.584,0.285,2019,0.308,7.2321,1.301648,0.933913,0.281529,2020,0.390843

In [10]:
combined_years = pd.merge(combined_years, df2021, how='outer', on='Country')
combined_years.head()

,Country,Happiness Score_x,GDP_x,Freedom_x,Generosity_x,Year_x,Trust (Government Corruption)_x,Happiness Score_y,GDP_y,Freedom_y,...,Freedom to make life choices_x,Generosity_y,Year_y,Perceptions of corruption_x,Happiness Score,GDP,Freedom to make life choices_y,Generosity,Year,Perceptions of corruption_y
0,Switzerland,7.587,1.39651,0.66557,0.29678,2015,0.41978,7.509,1.52733,0.58557,...,0.921337,0.269056,2020,0.303728,7.571,1.566,0.919,0.204,2021,0.292
1,Iceland,7.561,1.30232,0.62877,0.43630,2015,0.14145,7.501,1.42666,0.56624,...,0.948892,0.362330,2020,0.711710,7.554,1.482,0.955,0.293,2021,0.673
2,Denmark,7.527,1.32548,0.64938,0.34139,2015,0.48357,7.526,1.44178,0.57941,...,0.951444,0.242793,2020,0.168489,7.620,1.502,0.946,0.208,2021,0.179
3,Norway,7.522,1.45900,0.66973,0.34699,2015,0.36503,7.498,1.57744,0.59609,...,0.955750,0.287985,2020,0.263218,7.392,1.543,0.960,0.249,2021,0.270
4,Canada,7.427,1.32629,0.63297,0.45811,2015,0.32957,7.404,1.44015,0.57370,...,0.933913,0.281529,2020,0.390843,7.103,1.447,0.915,0.246,2021,0.415

In [11]:
combined_years.to_csv(r'../HappynessYearsMerged.csv')

In [20]:
combined_years.columns=["Country" ,"Happiness2015",	"GDP2015",	"Freedom2015",	"Generosity2015",	"Year2015",	"Corruption2015",
"Happiness2016",	"GDP2016",	"Freedom2016",	"Generosity2016",	"Year2016",	"Corruption2016",
"Happiness2017",	"GDP2017",	"Freedom2017",	"Generosity2017",	"Year2017",	"Corruption2017",
"Happiness2018",	"GDP2018",	"Freedom2018",	"Generosity2018",	"Year2018",	"Corruption2018",
"Happiness2019",	"GDP2019",	"Freedom2019",	"Generosity2019",	"Year2019",	"Corruption2019",
"Happiness2020",	"GDP2020",	"Freedom2020",	"Generosity2020",	"Year2020",	"Corruption2020",
"Happiness2021",	"GDP2021",	"Freedom2021",	"Generosity2021",	"Year2021",	"Corruption2021"]

In [21]:
combined_years

,Country,Happiness2015,GDP2015,Freedom2015,Generosity2015,Year2015,Corruption2015,Happiness2016,GDP2016,Freedom2016,...,Freedom2020,Generosity2020,Year2020,Corruption2020,Happiness2021,GDP2021,Freedom2021,Generosity2021,Year2021,Corruption2021
0,Switzerland,7.587,1.39651,0.66557,0.29678,2015,0.41978,7.509,1.52733,0.58557,...,0.921337,0.269056,2020,0.303728,7.571,1.566,0.919,0.204,2021,0.292
1,Iceland,7.561,1.30232,0.62877,0.43630,2015,0.14145,7.501,1.42666,0.56624,...,0.948892,0.362330,2020,0.711710,7.554,1.482,0.955,0.293,2021,0.673
2,Denmark,7.527,1.32548,0.64938,0.34139,2015,0.48357,7.526,1.44178,0.57941,...,0.951444,0.242793,2020,0.168489,7.620,1.502,0.946,0.208,2021,0.179
3,Norway,7.522,1.45900,0.66973,0.34699,2015,0.36503,7.498,1.57744,0.59609,...,0.955750,0.287985,2020,0.263218,7.392,1.543,0.960,0.249,2021,0.270
4,Canada,7.427,1.32629,0.63297,0.45811,2015,0.32957,7.404,1.44015,0.57370,...,0.933913,0.281529,2020,0.390843,7.103,1.447,0.915,0.246,2021,0.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,Northern Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.101,1.068,0.751,0.212,2021,0.905
169,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.733163,0.425990,2020,0.690718,5.051,0.367,0.697,0.465,2021,0.746
170,Hong Kong S.A.R. of China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.779834,0.288281,2020,0.420607,5.477,1.525,0.717,0.232,2021,0.403
171,Maldives,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.853963,0.224198,2020,0.824211,5.198,1.115,0.854,0.204,2021,0.825

In [ ]:
# Rename our _x columns to "2013 Wins", "2013 Losses", and "2013 Draws"
combined_years = df1516.rename(columns={"Year_x":"Year","Happiness Score_x":"2015Happiness","GDP_x":"2015GDP", 
                                "Generosity_x": "2015Generosity"})

# Rename our _y columns to "2014 Wins", "2014 Losses", and "2014 Draws"
combined_years = df1516.rename(columns={"Year_y":"Year","Happiness Score_y":"2016Happiness","GDP_y":"2016GDP", 
                                "Generosity_y":"2016Generosity"})

combined_years.head()

In [ ]:
combined_years = pd.merge(combined_years,y_2017, how='outer', on='Country')
combined_years

In [ ]:
combined_years = combined_years.rename(columns={"Year_y":"Year","Happiness Score_x":"2017Happiness","GDP_y":"2016GDP", 
                                "Generosity_x":"2017Generosity"})

In [22]:
combined_years.to_csv(r'../HappynessYearsMerged.csv')

In [ ]:
west=plt.plot(y_2015.loc[y_2015['Region']=='Western Europe']['Happiness Score'],y_2015.loc[y_2015['Region']=='Western Europe']['Generosity'],color="yellow",label="Western Europe")
sub=plt.plot(y_2015.loc[y_2015['Region']=='Sub-Saharan Africa']['Happiness Score'],y_2015.loc[y_2015['Region']=='Sub-Saharan Africa']['Generosity'],color="green",label="Western Europe")# titles and labels
plt.title("Annual Hours Worked Since 1950")
plt.xlabel("Year")
plt.ylabel("Annual Hours Worked")
# places legend outside plot
plt.legend(loc='center left', bbox_to_anchor=(1, .5))
plt.grid()
plt.show()